### ISSUE TITLE
Add Quick-Info in «Reports» for query language

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#102]

**Comment by saemideluxe** [comment]
I added a "help" button to get information about possible values for columns, please check on the demo instance at https://connect.basx.ch/reports/reports/report/edit/1
There are many things we can still improve like
- Design/UI
- Displaying more field (currently we show only a subset of possible fields, the ones which are straight-forward to detect)
- Describe fields via ForeignKeys better (currently this is limit to span only one relation, but spanning many relations could be helpfull sometimes).
