### ISSUE TITLE
Redesign Person Detail screen – Tab "Stammdaten" (natural person)

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#104]
- [ ] Implement as shown 
- [ ] Section _Kontaktdaten_ is subject to change > instead, better show a data table with inline editing ?)
- [ ] Click on Edit-Button opens a transactional modal pop up
- [ ] use fields for legal persons in separate page "Manage legal person" (is a separate ui mockup required?)

[see current Sketch document for details](https://www.sketch.com/s/6023b9d5-7942-4477-8970-facb0651c7f4/p/E6881FD2-5501-41EF-AD1F-83E3C4CE5E22)

![Natürliche-Person-verwalten_Tab-Stammdaten_max-1584px-16 column](https://user-images.githubusercontent.com/74606126/126169791-256c6761-27a7-4215-8e65-aeefeff9c8af.png)

<img width="1113" alt="Bildschirmfoto 2021-07-19 um 15 44 05" src="https://user-images.githubusercontent.com/74606126/126169738-3b499570-7b8c-4783-8046-5a99fa316f93.png">

**Comment by frederikbugglin** [comment]
@wipascal 

- [ ] set border-color to _gray-10_ (instead of gray-20):
<img width="396" alt="Bildschirmfoto 2021-08-09 um 12 56 32" src="https://user-images.githubusercontent.com/74606126/128697216-cb6ab5d3-abe2-4865-a141-852a08cf4b23.png">

- [ ] set border-with to 2px (gray-10)
<img width="915" alt="Bildschirmfoto 2021-08-09 um 13 07 09" src="https://user-images.githubusercontent.com/74606126/128697510-1c854214-d5d5-47e9-91e0-85babc48fd17.png">

**Comment by wipascal** [comment]
@frederikbugglin, @saemideluxe
Since this change affects BasxConnect I think we need to keep this compatible with peacewatch.
After the redesign we will have only two address types ("Domizil" and "Korrespondenz").
How do we map the four existing address ones (Business, Domicil, Postbox and Private) to the two remaining ones? And what do we do if Peacewatch even has instances where a Person has multiple addresses of the same type?

**Comment by saemideluxe** [comment]
As far as I am concerned, compatability with peacewatch should not be relevant.

**Comment by wipascal** [comment]
@frederikbugglin 
A first version of the new UI is implemented.
There are still quite some differences. I think we need to focus on new features for the moment, so I created a separate issue for the remaining todos: https://github.com/basxsoftwareassociation/basxconnect/issues/156
While testing, please put all non-critical stuff into the new issue which I mentioned and for critical bugs create separate issues.
