### ISSUE TITLE
Changing email address in bC deletes Mailchimp contact and creates a new Mailchimp contact with the same settings

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#128]
Test case (UM Dev Umgebung): 

Action: change email address in bC
expected result: old MC contact deleted, new contact added in Mailchimp

**Comment by saemideluxe** [comment]
Testing auf urbanmosaic.clients2.basx.dev

**Comment by wipascal** [comment]
@frederikbugglin you were right, there was a bug. Should now be fixed. Can you try again?

**Comment by wipascal** [comment]
@frederikbugglin
I fixed a couple of things.
Could you test again?
