### ISSUE TITLE
Add filter option to data table toolbar "person overview"

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#13]
**State = filter active**
![max-1584px-16 column_PERSONEN_Übersicht_V2_Data-Table_Multiselect-Filter_state-closed_active](https://user-images.githubusercontent.com/74606126/111163846-c36d1e00-859d-11eb-9252-1155f273c3c6.png)

**State = filter inactive (closed)**
![max-1584px-16 column_PERSONEN_Übersicht_V2_Data-Table_Multiselect-Filter_state-closed](https://user-images.githubusercontent.com/74606126/111163855-c49e4b00-859d-11eb-8b7e-39ed785aa557.png)

**State = open (active)**
![max-1584px-16 column_PERSONEN_Übersicht_V2_Data-Table_Multiselect-Filter_state-open](https://user-images.githubusercontent.com/74606126/111163856-c536e180-859d-11eb-9d53-a86576895b21.png)

**Comment by frederikbugglin** [comment]
der Filter kann gem. PWS umgesetzt werden: 
![max-1584px-16 column_PERSONEN_Übersicht_V2_Data-Table_Multiselect-Filter_state-open_layout](https://user-images.githubusercontent.com/74606126/111969193-43453c00-8afa-11eb-89e4-de24fca1a504.png)

![max-1584px-16 column_PERSONEN_Übersicht_V2_Data-Table_Multiselect-Filter_state-open](https://user-images.githubusercontent.com/74606126/111969198-44766900-8afa-11eb-80b4-cc96136d7de3.png)

**Comment by saemideluxe** [comment]
We need to adjust the spacing, right? I already uploaded an implementation to our test/stagning area but need to adjust the spacing I guess.
In any case there are still two issues left:
- The number of selected checkboxes is not yet displayed (working on that)
- The three main categories of persons (natural/legal/association) can be selected independently. The design shows that they would have a *mixed* state. However, in case somebody wants to select e.g. all legal persons *without* any sub-categorie (church, city, company, etc) that would not be possible. Even if a sub-category is required to be set one would want to have the option to filter for persons with unassigned subcategories. E.g. for the currently imported data there are no sub-categories defined for legal persons.

**Comment by frederikbugglin** [comment]
> We need to adjust the spacing, right?

yep, as well as the background color (to #fff)

**Comment by frederikbugglin** [comment]
> * The three main categories of persons (natural/legal/association) can be selected independently. The design shows that they would have a _mixed_ state. However, in case somebody wants to select e.g. all legal persons _without_ any sub-categorie (church, city, company, etc) that would not be possible. Even if a sub-category is required to be set one would want to have the option to filter for persons with unassigned subcategories. E.g. for the currently imported data there are no sub-categories defined for legal persons.

this should not be problematic

**Comment by saemideluxe** [comment]
Ok, implemented. One note on the buttons: They have to be either modal-buttons and span the whole width of the container/panel or the are normal buttons and are right-aligned. If we want to have them modal-button-size (as suggested in the picture) and **not** span the whole width we need a rule how wide the buttons should be.

**Comment by frederikbugglin** [comment]
- [ ] Remove margin below parent category (see below)
- [ ] German translation of modal buttons
- [ ] add filter count to toolbar bar
<img width="976" alt="Bildschirmfoto 2021-03-30 um 11 30 33" src="https://user-images.githubusercontent.com/74606126/112967263-6354ab00-914b-11eb-93f4-20d18d155fcb.png">

**Comment by saemideluxe** [comment]
Fixed
