### ISSUE TITLE
Modal popup: E-Mail Abonnemente

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#131]
- [x] Sync email interests with MC
- [ ] Sync Mailchimp status
- [x] Design modal popup @frederikbugglin

**Comment by wipascal** [comment]
@frederikbugglin
"Sync email interests with MC" is already done and can be tested...
"Sync Mailchimp status" for that one we need more discussion (also with Beat and Michelle)

**Comment by wipascal** [comment]
I will close this issue. If the customers need more features for the mailchimp synchronization, I am sure they will tell us.
