### ISSUE TITLE
Modal pop: Versand-Einstellungen

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#132]

**Comment by frederikbugglin** [comment]
tested on UM DEV. seems to work, although I am not so happy with the multi-select dropdown. But I presume, that's easier to implement, than the toggle I had sketched out.

**Comment by wipascal** [comment]
> tested on UM DEV. seems to work, although I am not so happy with the multi-select dropdown. But I presume, that's easier to implement, than the toggle I had sketched out.

I agree. This multi-select dropdown is what django produces automatically. Can you repost your original sketch in this issue, so that we both know which sketch is the "right" one?

**Comment by frederikbugglin** [comment]
![E-Mail_Abonnemente-bearbeiten_Modal_Transactional-Popup_Small](https://user-images.githubusercontent.com/74606126/132199710-9eeb8a3e-5234-4b44-8477-979e60bb8bf2.png)

**Comment by wipascal** [comment]
I have created an issue for a new widget which can replace the multiselect dropdown: https://github.com/basxsoftwareassociation/basxconnect/issues/157
