### ISSUE TITLE
Wrong currency displayed when importing donations

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#135]
**Describe the bug**
When importing donations using the Zuwendungsimport wizard, the euro sign is displayed. (seen PWS Life instance)

**To Reproduce**
1. Go to 'Zuwendungen' (see error in the data table overview)
2. Click on 'Zuwendungsimport'
3. Select file to import, click 'weiter'

**Expected behavior**
Swiss Francs CHF should be the default currency throughout the whole instance.

**Screenshots**
In data table list overview:
<img width="1308" alt="Bildschirmfoto 2021-08-17 um 16 03 48" src="https://user-images.githubusercontent.com/74606126/129746342-87bf8453-ed4b-4439-81e4-aba0acf01076.png">

In Zuwendungsimport-Wizard
<img width="1552" alt="Bildschirmfoto 2021-08-17 um 16 31 45" src="https://user-images.githubusercontent.com/74606126/129746346-61f33791-73c5-4ece-9470-d173ff7b6c68.png">

**Desktop (please complete the following information):**
 - OS:  macOS
 - Browser: Brave
 - Version 1.28.105

**Comment by frederikbugglin** [comment]
tested on UM DEV. please push to PWS LIVE as well.

**Comment by saemideluxe** [comment]
Updated on production.
