### ISSUE TITLE
Add download button in data table toolbar  

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#14]
export selected items to xls-File.

**Comment by saemideluxe** [comment]
Bulk-download is there and working. There is a small catch however: When selecting "all" entries and then *deselecting* a few items in rows below, the unselected items will still be exported. I think this is a minor issue and maybe deselecting single items after selecting should not even be a feauture... What do you think?

**Comment by frederikbugglin** [comment]
- [ ] BUG: At the moment, not only the selected items are be exported but instead _all_ items are exported (even though only a few (not all) items have been selected previously) (Brave 1.22.99, User admin)

**Comment by saemideluxe** [comment]
Should be fixed.
