### ISSUE TITLE
Person overview: right align email icon in column 

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#15]

**Comment by frederikbugglin** [comment]
issue is not resolved on my side (user admin)

**Comment by saemideluxe** [comment]
Sorry, Github closes the Issue automatically as soon as I push a code to github. But the code has not been deployed immediately.

**Comment by tpokorra** [comment]
@saemideluxe: you could work on a branch, and then merge the branch into main, when you are deploying it.
then the bug would only be closed, as soon as the commit arrives on main branch

**Comment by saemideluxe** [comment]
Thanks for the tip @tpokorra , will do it like that. I guess then I will pull and merge on production and after the upgrade on production push back to Github.

**Comment by saemideluxe** [comment]
@frederikbugglin this is now activated on our testsite p########.ba##.ch
