### ISSUE TITLE
UI improvement: New widget which can optionally replace multiselect

### ISSUE THREAD

**Issue by wipascal** [basxsoftwareassociation/basxconnect#157]
At some places it would be better to have multiple checkboxes instead of a multiselect dropdown.
E.g. when editing mailing subscriptions it is not user-friendly to have a popup with just the multiselect. It would be better to have multiple check boxes directly in the modal. 
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/11404846/133985463-2088c6d5-6436-428c-9d7a-976c79400765.png">

**Comment by saemideluxe** [comment]
This is already possible if you specify the form widget to be "django.forms.CheckboxSelectMultiple". The bread.forms code will create the according checkboxes. You can check the person browse view filter if you want to see a form using it. However, I think there is a small issue with the labels... I the current forms refactoring this will be improved.
