### ISSUE TITLE
BUG: Error 500 upon click on menu item "Settings/General"  

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#16]
<img width="912" alt="Bildschirmfoto 2021-03-15 um 14 58 36" src="https://user-images.githubusercontent.com/74606126/111165112-f368f100-859e-11eb-9224-332ee8cce8c6.png">

**Comment by saemideluxe** [comment]
Fixed, the system needs one person to be marked as "owner" of the database, the settings has not been made yet.
