### ISSUE TITLE
New Person Wizard should allow to enter an email address

### ISSUE THREAD

**Issue by saemideluxe** [basxsoftwareassociation/basxconnect#171]
When adding a new person it is not possible to enter an email address directly, only a postal address. We need also to be able to enter an email address in that wizard.

**Comment by saemideluxe** [comment]
Will be included in next minor release

**Comment by saemideluxe** [comment]
Done on public demo

**Comment by freebeat** [comment]
Looks, cool, can we have this on urbanmosaic?
