### ISSUE TITLE
Improve mailchimp sync

### ISSUE THREAD

**Issue by freebeat** [basxsoftwareassociation/basxconnect#187]
Here a few improvements for the mailchimp sync:
- I think the function should not be under settings: Suggestion: New menu Items tools
- Translations missing
- Previous Executions:
  - Column "Person records with errors" instead of Invalid Persons, add first and last name, 1 per line
  - Column "New person records" instead of New Persons, add first and last name, 1 per line
  - Inverse sort (latest first)

**Comment by wipascal** [comment]
@freebeat Done. I changed the wording a little bit, feel free to request me to change it back to exactly what you suggested.

**Comment by freebeat** [comment]
Better, thanks. Further minor improvements would IMO be: 
- Move help text into help pop-up
- Fix indents in column titles (see screenshot)
![grafik](https://user-images.githubusercontent.com/32923789/144808145-3f7a4e51-b9d6-4bee-b6b2-2530b13eb25f.png)
- Add translation for "synchronization results"

Priority to be discussed

**Comment by freebeat** [comment]
New issues created for help pop up and indents. Remains the translation

**Comment by saemideluxe** [comment]
Testing auf urbanmosaic.clients2.basx.dev

**Comment by freebeat** [comment]
Ok, bestens, danke
