### ISSUE TITLE
Mailchimp sync: Handle cleaned addresses

### ISSUE THREAD

**Issue by freebeat** [basxsoftwareassociation/basxconnect#189]
Here my suggestion how to handle cleaned e-mail addresses from mailchimp in basx Connect:

- Problem: In the current synchronisation report, cleaned addresses in mailchimp appear as "Invalid Persons" (column header to be changed to "Person records with errors" in another issue) in every execution.
- Goal: A way to accept that fact that they are cleaned, but freshly cleaned addresses, speciall from existing persons, should be listed
- Solution: We import the contact anyway, including the email address, but with special status cleaned in the email subscription block. Next sync, as there is no change in status of that address, there is now new entry in the report

**Comment by wipascal** [comment]
@freebeat Done. Cleaned mailchimp subscriptions are now not filtered out anymore.

**Comment by freebeat** [comment]
Works, thanks.
