### ISSUE TITLE
[Task] No permission to add tags as non admin

### ISSUE THREAD

**Issue by freebeat** [basxsoftwareassociation/basxconnect#199]
As non admin user I tried to add a tag which fails (because I don't have permission for the vocabulary?)

**Comment by saemideluxe** [comment]
You mean create a new tag or adding an existing tag to a person?
For the first one your users need to according permissions. I looked on production instance and if you have the technical staff role then you should be able to do this. I think Pascal changed the permission at some point, can you try to do this again please?

**Comment by freebeat** [comment]
Works, thanks
