### ISSUE TITLE
[BUG] Add/Edit subscription broken

### ISSUE THREAD

**Issue by freebeat** [basxsoftwareassociation/basxconnect#200]
System: UMCH
Tab "Versand" --> Edit (or add) Subscription produces a list of all persons

**Comment by wipascal** [comment]
@freebeat I don't know what you mean with "list of all persons", but I agree that adding and editing subscriptions didn't work. If fixed that just now. (And even managed to subscribe my email address wiesmann@basx.ch for the English prayer bulletin!!!)

**Comment by freebeat** [comment]
Seems to be a permission problem, as it works properly as admin, but not as beat

**Comment by saemideluxe** [comment]
@freebeat your users role has the "Technical Staff" role assigned. This role has a fixed set of permissions assigned, but firstly not all permissions and secondly will not get automatically get permissions for new models/tables.

If you want a user that has always all permissions I recommend you enable the ```is_superuser``` attribute on your user. This will treat your user like it always has all permissions. Besides this there is not much more "power" to users with super-abilities (like making changes to the file-system outside of the upload folder or updating installed packages).

FYI: The ```is_staff``` attribute tells if a user can login to the Django admin backend (that is just the default Django-semantic of the attribute, we could repurpose that for our own system if desired).

**Comment by wipascal** [comment]
Yes, I added some new Models but did not add new permissions to "Technical Staff". I added them now.

**Comment by freebeat** [comment]
Thanks, works
