### ISSUE TITLE
Fix some translations

### ISSUE THREAD

**Issue by saemideluxe** [basxsoftwareassociation/basxconnect#213]
(Issues transfered from private repo at https://github.com/basxsoftwareassociation/basxconnect_urbanmosaic/issues/32)

The following strings are untranslated:

Block "Personal Data" --> Edit
Block "Adresses" --> Add
Blocks "Tags" --> Edit

Need to mark the strings as translatable.

**Comment by dward2nd** [comment]
Done in #214

**Comment by saemideluxe** [comment]
Ready for testing on connect.basx.ch. UM projects will automatically follow in the next update of the according instances.

**Comment by freebeat** [comment]
Perfect, thanks
