### ISSUE TITLE
[BUG] Missing translation in edit e-mail popup

### ISSUE THREAD

**Issue by freebeat** [basxsoftwareassociation/basxconnect#223]
![grafik](https://user-images.githubusercontent.com/32923789/147541025-f90cb53e-715e-4cbb-91d1-ecd2bea7af38.png)

**Comment by saemideluxe** [comment]
@dward2nd This is likely a missing translation inside basxconnect.

**Comment by dward2nd** [comment]
@saemideluxe I made a pull request in #224 .

**Comment by freebeat** [comment]
Works nicely, thanks
