### ISSUE TITLE
Active search bar improvements

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#23]
- [x] display each found item on one single line
- [x] emphasize found search term _semibold 600_
- [x] _0% opacity_ for search results background
- [x] include a loading indicator. when search completed, display number of found items instead (e.g. 3 items found)
- [x] enable search by _person id_
- [x] Default state for Search bar: _active_ (background-color=#fff)

![Active Search bar results](https://user-images.githubusercontent.com/74606126/112120667-caf47e80-8bbe-11eb-92d2-c871e28d050a.png)

**include person id in search results**
<img width="265" alt="Bildschirmfoto 2021-03-16 um 10 44 09" src="https://user-images.githubusercontent.com/74606126/111291416-7776b380-8647-11eb-8aa1-ce8ff55dedf7.png">

> high prio

**Comment by saemideluxe** [comment]
Regarding the loading indicator: Would it be acceptable to take it inside the input field? It would make parts of the implementation more clear because the loading indicator is technically more related to the search input than the content of the returned answer.

**Comment by saemideluxe** [comment]
Okay, this is ready for review. Two things which differ from the screenshots are:
1. The loading indicator
2. The width of the result box is the same as the table and not the same as the input box. This is related to how carbon design structures the toolbar and the datatable. They are two separate containers and the toolbar does not allow having visible overflow containers which makes alignment via CSS basically impossible. There is no way to get the correct width of the search input except using javascript and setting the width after the page has been loaded and running the script. So, there would be a way to implement the feature but I wonder how important it is. If it is really too unpleasent for the eye I can spend a bit more time trying to find a better way to get things aligned correctly.

**Comment by frederikbugglin** [comment]
> Regarding the loading indicator: Would it be acceptable to take it inside the input field? It would make parts of the implementation more clear because the loading indicator is technically more related to the search input than the content of the returned answer.

yes, this is acceptable — and even better.
