### ISSUE TITLE
Export *person.id* in Reports  

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#26]
column title in exported file: Stamm-Nr.

(needed as a merge field in Word for mailings (e.g. as an identifier for postal returns))

**Comment by saemideluxe** [comment]
Done. The number is now in the last column, which is asthetically not great. But the order can be changed manually if desired (there is now an "order" for each column),

**Comment by frederikbugglin** [comment]
> But the order can be changed manually if desired (there is now an "order" for each column

This functionality is only shown in our test instance (but not the on productive instance.)
