### ISSUE TITLE
Set max. column width for pages "Settings/Persons and Relations"

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#29]
- [ ] data-table-container max. width = 6 columns (see #28)

**Comment by saemideluxe** [comment]
6 columns has not a clear implementation in the carbon design css. Assuming we talk about fixed columns and one column consists of 10 mini units I set the max-width to 480 (8px * 10 * 6)

**Comment by frederikbugglin** [comment]
> Let me know whether that works or not.

looks good to me
