### ISSUE TITLE
Add proper CI (github workflows?)

### ISSUE THREAD

**Issue by saemideluxe** [basxsoftwareassociation/basxconnect#3]
Things needed to do:

- black formatting
- flake8 checks
- isort (ordering import statements)
- bandit (dependency vulnerability checks)
- run tests and coverage
- update pip package if there is a new release

**Comment by tpokorra** [comment]
Github offers CI services for free for open projects.
"GitHub Actions is available with GitHub Free, GitHub Pro, GitHub Free for organizations, GitHub Team, GitHub Enterprise Cloud, GitHub Enterprise Server, and GitHub One. GitHub Actions is not available for private repositories owned by accounts using legacy per-repository plans."
see https://docs.github.com/en/free-pro-team@latest/actions/guides/about-continuous-integration

see https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python
with flake8.

black formatting: https://github.com/marketplace/actions/black-code-formatter
and https://github.com/psf/black/actions/runs/17913292/workflow
