### ISSUE TITLE
Display current user name in ui header

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#34]

**Comment by frederikbugglin** [comment]
- [ ] Display current username left of logout icon
- [ ] Pull company name from Settings/General/Name
- [ ] Move name (currently before displayed before the product name) to its new position and format it as shown
- [ ] Format product name basx Connect as shown (basx: 400 Connect: 600) 

![header new](https://user-images.githubusercontent.com/74606126/111993443-ed32c180-8b16-11eb-918f-3969a1bb2795.png)

**Comment by saemideluxe** [comment]
How should we determine the distance between product name and name? If we take the width of the navigation menu wouldn't it look unclean when the menu is collapsed?

**Comment by saemideluxe** [comment]
Okay, implemented. As discussed the $general.settings.name will be pulled to the left and the platform name will be replaced with the basxconnect logo when the navigation menu is collapsed. Please note that the position of $general.settings.name will *not* change immediately after the menu is collapsed but only after the next page relead. We could do this with a samll javascript-hack but it seemd not to be worth the effort and the additional code for such a seldomly triggered event.

**Comment by frederikbugglin** [comment]
the currently logged in $username is missing (placed right next to the logout button)

**Comment by saemideluxe** [comment]
We displayed the full name of the user instead of the username. Is fixed now.

**Comment by saemideluxe** [comment]
The name of the platform owner is no longer aligned with the menu, fix again.

**Comment by saemideluxe** [comment]
Okay, fixed again but not updated yet. Will go through with the next update.
