### ISSUE TITLE
Mailchimp Integration (Exploration)

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#37]

**Comment by frederikbugglin** [comment]
https://www.cleverreach.com/de/
https://www.mailerlite.com/

https://sendgrid.com/
https://www.mailgun.com/

**Comment by frederikbugglin** [comment]
Top priority: Mailchimp

Questions:
- Level of synchronization of subscriptions/unsubscriptions? Manual import/export vs. half automated vs. fully automated sync? 
- How do we manage multiple mailing lists/topics per person?

**Comment by saemideluxe** [comment]
Considering this done because it was mostly focused on the exploratin of the mailchimp API and possible implementations. We can open new issues for business-oriented feature requests.
