### ISSUE TITLE
UI Improvements of tab «Relationship»

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#46]
<img width="1390" alt="Bildschirmfoto 2021-04-06 um 12 05 05" src="https://user-images.githubusercontent.com/74606126/113695817-952cbb00-96d1-11eb-82a7-6c1c28607229.png">

- [ ] Person A is always the currently displayed person > there column "Person A" is _not_ necessary
- [x] Data table title missing
- [ ] data table inline adding for new relationship (instead of opening a new page) 
- [x] Rename "Beziehungen" to "Verknüpfungen"
- [x] Removal/edit function of existing relationship is missing
- [x] Person no. in brackets is missing
- [x] Person B: cell must be a link

**Comment by wipascal** [comment]
Not sure about the first requirement: Person A is NOT always the currently displayed person. e.g. with the "arbeitet bei" relationship, the employee will be listed as Person B.
