### ISSUE TITLE
UI improvements of tab "Stammdaten"

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#47]
legal persons
![max-1584px-16 column_PERSONEN_Juristische-Person_Tab-Stammdaten_Edit-mode](https://user-images.githubusercontent.com/74606126/113743279-caea9780-9703-11eb-8aec-fdee77bb2986.png)

legal persons (view mode, tab only)
![max-1584px-16 column_PERSONEN_Juristische-Person_Tab-Stammdaten_View-mode](https://user-images.githubusercontent.com/74606126/113743271-c8883d80-9703-11eb-819b-44424f83d0eb.png)

individual persons
![max-1584px-16 column_PERSONEN_Natürliche-Person_Tab-Stammdaten_Edit-mode](https://user-images.githubusercontent.com/74606126/113743283-cb832e00-9703-11eb-9310-2f27eb4302a5.png)

handoff with measurements
![max-1584px-16 column_PERSONEN_Juristische-Person_Tab-Stammdaten_Edit-mode_Vermassung](https://user-images.githubusercontent.com/74606126/113743275-c9b96a80-9703-11eb-9c83-ccbc5ba250df.png)

**Comment by wipascal** [comment]
Hi @frederikbugglin , currently we also show a "Type" (e.g. "Stiftung") for legal persons. This field is not on the Screenshot you sent. Is this intended?

**Comment by wipascal** [comment]
Hi @saemideluxe, @frederikbugglin 
I think we can close this issue. I did not implement everything as some changes would have been too complicated. But I believe the important things are done...

**Comment by saemideluxe** [comment]
Can we close already or not yet?

**Comment by wipascal** [comment]
I am still working on some stuff. I think we will need one call this week to discuss what we want and then another one next week to review if the final result is ok and then we can hopefully close it...
