### ISSUE TITLE
renaming issues: no module named basxconnect.core.layouts.editperson_association

### ISSUE THREAD

**Issue by tpokorra** [basxsoftwareassociation/basxconnect#61]
I have issues building:

```
[00:06:59]   File "/home/django/basxconnect_demo/.venv/lib/python3.7/site-packages/basxconnect/core/views.py", line 21, in <module>
[00:06:59]     from basxconnect.core.layouts.editperson_association import editperson_association_tabs
[00:06:59] ModuleNotFoundError: No module named 'basxconnect.core.layouts.editperson_association'
```

I get this error in basxconnect_demo, when I run either of these commands:

```
. .venv/bin/activate && python manage.py migrate
. .venv/bin/activate && python manage.py compress --force
```

**Comment by tpokorra** [comment]
https://github.com/basxsoftwareassociation/basxconnect/blob/main/basxconnect/core/views.py#L21
https://github.com/basxsoftwareassociation/basxconnect/blob/main/basxconnect/core/layouts/editpersonassociation.py

**Comment by wipascal** [comment]
Oops.. could you state the version (commit hash) of basxconnect you are using?

**Comment by wipascal** [comment]
Oh now I see, I fixed it but forgot to commit the file.

**Comment by wipascal** [comment]
I pushed the changes. Can you try again now?

**Comment by tpokorra** [comment]
yes, that worked! Thank you!
