### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#66]
https://www.carbondesignsystem.com/patterns/login-pattern/#design-and-layout
https://docs.djangoproject.com/en/3.2/topics/auth/default/

**Comment by frederikbugglin** [comment]
see UI (to be discussed)
[UserAuthentifaction.pdf](https://github.com/basxsoftwareassociation/basxconnect/files/6570524/UserAuthentifaction.pdf)

**Comment by frederikbugglin** [comment]
see screenshots (to be discussed)
![LoginView_empty](https://user-images.githubusercontent.com/74606126/120201460-c1723d00-c225-11eb-82dc-06bf2d8900c9.png)
![LoginView_filled_Error](https://user-images.githubusercontent.com/74606126/120201464-c2a36a00-c225-11eb-8372-5374d8c4a273.png)
![LoginView_filled](https://user-images.githubusercontent.com/74606126/120201467-c3d49700-c225-11eb-9230-b6e856166a24.png)
![PasswordChangeDoneView](https://user-images.githubusercontent.com/74606126/120201469-c3d49700-c225-11eb-813c-d91529c9b553.png)
![PasswordChangeForm](https://user-images.githubusercontent.com/74606126/120201471-c46d2d80-c225-11eb-8cfa-07f1b68ce1ac.png)
![PasswordResetDoneView](https://user-images.githubusercontent.com/74606126/120201473-c505c400-c225-11eb-94e6-0c6b08e8d057.png)
![PasswordResetForm](https://user-images.githubusercontent.com/74606126/120201477-c59e5a80-c225-11eb-9983-886189ff9f6d.png)

**Comment by frederikbugglin** [comment]
background gradient = linear from 0F62FE to 0008C9 100 Opacity

**Comment by saemideluxe** [comment]
My deviation form the design suggestion so far are:
- Username and password will be displayed on the sam page (easier to implement for now)
- No checkbox for "Remember me", Django has a default value of 2 weeks remembering a users session (which can be adjusted per database-instance). I think this is okay, most people who don't want to keep their logins will either logout or automatically clear cookies when the browser is closed (which will log them out as well).

Is this acceptable? Let me know your thoughts.

**Comment by frederikbugglin** [comment]
All deviations from the design are ok. Tested on the UM DEV instance as the DEMO instance does not work at the moment. Results:

- [ ] requesting a new passwort (link: forgot password) does not work > no email received from the server
- [ ] minor cosmetic issue: both footer action buttons should be 64px in height (instead of 48px)

**Comment by saemideluxe** [comment]
The password reset was not working because the basx.ch mailserver rejected the password reset email (because of an ambiguous FROM in the email), this should be fixed now. 
Cosmetic is fixed as well.

**Comment by frederikbugglin** [comment]
I still do not receive an email from the server.

**Comment by frederikbugglin** [comment]
on UM dev, I do receive the reset instructions, however the reset link does not work:

<img width="496" alt="Bildschirmfoto 2021-08-16 um 10 32 13" src="https://user-images.githubusercontent.com/74606126/129535067-8daf8374-6993-4267-9039-eb6fd7a4374e.png">
