### ISSUE TITLE
Add filtered fields to Excel file download

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#70]
When a filter is applied and an Excel file will be downloaded, the content of the selected fields should be added in columns: _person type, person sub type, tags, language, state_:

<img width="934" alt="Bildschirmfoto 2021-05-18 um 11 08 42" src="https://user-images.githubusercontent.com/74606126/118624618-9cafab80-b7c9-11eb-807d-411c6b558e17.png">
 
Please make sure this is added to the next release

**Comment by saemideluxe** [comment]
I will only add tags and language because person sub-type and state are already displayed. How imporant to you think is the "person type" column? Since we do not display it in the web-view I thought we do not need to display it in the excel view as well.
